name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.20', '1.21']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Go ${{ matrix.go }} (${{ matrix.os }})

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run vet
        run: go vet ./...

      - name: Test
        run: go test -race ./...
